addSbtPlugin("org.scoverage" % "sbt-scoverage"   % "2.0.8")
addSbtPlugin("org.scalameta" % "sbt-scalafmt"    % "2.5.0")
addSbtPlugin("ch.epfl.scala" % "sbt-scalafix"    % "0.11.0")
addSbtPlugin("dev.zio"       % "zio-sbt-website" % "0.3.5")
addSbtPlugin("com.github.sbt" % "sbt-site-paradox" % "1.5.0")
addSbtPlugin("com.github.sbt" % "sbt-ghpages" % "0.8.0")